kddcup2018_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from submit import views as submit_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', submit_views.submit_form_view),
    path('submit/', include('submit.urls')),
    path('mysubmission/', include('mysubmission.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('datachart/', include('visualize.urls')),
    path('scoresimulator/', include('scoresimulator.urls')),
    path('visualize/', include('visualize.urls')),
    path('update/', submit_views.update_view) #スコアとかを再計算する
]

mysubmission/urls.py
from django.urls import path
from mysubmission import views

app_name = 'mysubmission'
urlpatterns = [
    path('', views.mysubmission_base_view, name='mysubmission_base_view'),
    path('detail', views.mysubmission_detail_view, name='mysubmission_detail_view'),
    path('detail_chart', views.mysubmission_detail_chart_view, name='mysubmission_detail_chart_view'),
]

submit/urls.py
from django.urls import path
from submit import views

app_name = 'submit'
urlpatterns = [
    path('', views.submit_form_view, name='submit_form'),
]

mysubmission/views.py
from django.shortcuts import render, redirect
from submit.models import ScoreModel, SubmitModel
import pandas as pd
from datetime import timedelta
import logging

logger = logging.getLogger(__name__)


# Create your views here.
def mysubmission_base_view(request):
    if request.method != 'POST':
        return render(request, 'mysubmission/mysubmission_base.html')

    # ユーザ名を入手
    username = request.POST['username']

    submits = SubmitModel.objects.filter(username=username)
    context = {'submits': submits}

    return render(request, 'mysubmission/mysubmission_list.html', context)

def mysubmission_detail_view(request):
    logger.info('request.method')
    if request.method == 'POST':
        submit_id = request.POST['submit_id']
    elif request.method == 'GET':
        submit_id = request.GET['submit_id']

    scores = ScoreModel.objects.filter(submit=submit_id)

    # for chart
    submit = SubmitModel.objects.filter(id=submit_id)[0]

    # label data
    label_data = {}
    for city in ['beijing','london']:
        dir_name = "bj" if city == "beijing" else "ld"
        temp_label_data = pd.DataFrame(index=[], columns=['station_id','record_time','PM2.5','PM10','NO2','CO','O3','SO2'])
        for p in pd.date_range(submit.score_date_start - timedelta(days = 1),submit.score_date_end + timedelta(days = 2)):
            temp = pd.read_csv("./competition_data/data/official_aq_master/"+dir_name+"/date/"+p.strftime("%Y-%m-%d") + ".csv")
            temp_label_data = pd.concat([temp_label_data,temp],axis=0)
        temp_label_data = temp_label_data.loc[:,['record_time','PM2.5','PM10','O3']].groupby(['record_time']).median()
        # 先頭行がnullだと怒られるからとりあえず
        temp_label_data.iloc[0, :] = 0
        # データに抜けがあるので、ガワを作る
        # ただ、最初のほうがnanだと怒られるので、最初の方のnanがない時間帯から始める
        temp = pd.DataFrame(index=pd.date_range(temp_label_data.index[0],(submit.score_date_end + timedelta(days = 2)).strftime("%Y-%m-%d") + ' 23:00:00', freq='H'))
        temp_label_data = temp_label_data.join(temp,how="outer")
        label_data[city] = temp_label_data

    # submit data
    submit_data_series = []
    submit_data = pd.read_csv("./submit/static/submit_files/"+submit.username+"/"+submit.filename)
    submit_data['stationId'] = submit_data['test_id'].str.split('#').apply(lambda x:x[0])
    submit_data['hour_num'] = submit_data['test_id'].str.split('#').apply(lambda x:x[1]).astype(int)
    # score_dateごとに処理
    for score_date in submit_data['score_date'].unique():
        base_datetime = pd.to_datetime(score_date) + timedelta(days = 1)
        temp_submit = submit_data.loc[submit_data['score_date'] == score_date]
        temp_submit['datetime'] = temp_submit['hour_num'].apply(lambda x:base_datetime + timedelta(hours = x))
        temp_submit_beiijng = temp_submit.loc[temp_submit['stationId'].str.contains('_aq')]
        temp_submit_beiijng = temp_submit_beiijng.loc[:,['datetime','PM2.5','PM10','O3']].groupby(['datetime']).median()
        temp_submit_london = temp_submit.loc[~temp_submit['stationId'].str.contains('_aq')]
        temp_submit_london = temp_submit_london.loc[:,['datetime','PM2.5','PM10','O3']].groupby(['datetime']).median()
        temp_submit_data = {}
        temp_submit_data['base_datetime'] = base_datetime
        temp_submit_data['beijing'] = temp_submit_beiijng
        temp_submit_data['london'] = temp_submit_london
        temp_submit_data['date'] = score_date
        submit_data_series.append(temp_submit_data)

    charts = []
    for city in ['beijing','london']:
        targets = ['PM2.5','PM10','O3'] if city == "beijing" else ['PM2.5','PM10']

        for target in targets:
            temp_dict = {'city':city,'target':target}
            temp_dict['chart_data_series'] = []
            temp_dict['chart_data_series'].append({
                'name':'label',
                'data':str(label_data[city][target].values.tolist()).replace('nan','null'),
                'start_dt':str(label_data[city].index[0])
                })
            # ここをsubmitのscoreごとにループ
            for sd in submit_data_series:
                temp_dict['chart_data_series'].append({
                    'name':'submit ' + sd['date'],
                    'data':str(sd[city][target].values.tolist()).replace('nan',''),
                    'start_dt':sd['base_datetime']
                    })
            charts.append(temp_dict)

    context = {
        'charts': charts,
        'scores': scores,
        'submit_id': submit_id,
        'submit_timestamp' : submit.submit_timestamp,
        'submit_username' : submit.username,
        'submit_filename' : submit.filename,
        'submit_score_avg' : submit.score_avg,
    }

    return render(request, 'mysubmission/mysubmission_detail.html', context)

def mysubmission_detail_chart_view(request):
    if request.method == 'POST':
        submit_id = request.POST['submit_id']
        city = request.POST['city']
        target = request.POST['target']
        score_date = request.POST['score_date']
    elif request.method == 'GET':
        submit_id = request.GET['submit_id']
        city = request.GET['city']
        target = request.GET['target']
        score_date = request.GET['score_date']
    scores = ScoreModel.objects.filter(submit=submit_id)

    # for chart
    submit = SubmitModel.objects.filter(id=submit_id)[0]

    # label data
    dir_name = city
    label_data = pd.DataFrame(index=[], columns=['station_id','record_time','PM2.5','PM10','NO2','CO','O3','SO2'])
    for p in pd.date_range(pd.to_datetime(score_date) - timedelta(days = 1),pd.to_datetime(score_date) + timedelta(days = 3)):
        temp = pd.read_csv("./competition_data/data/official_aq_master/"+dir_name+"/date/"+p.strftime("%Y-%m-%d") + ".csv")
        label_data = pd.concat([label_data,temp],axis=0)
    label_data_stations = {}
    for station in label_data['station_id'].unique():
        temp_label_data = label_data.loc[label_data['station_id'] == station,['record_time',target]].set_index('record_time')
        # 先頭行がnullだと怒られるからとりあえず
        temp_label_data.iloc[0, :] = 0
        # データに抜けがあるので、ガワを作る
        # ただ、最初のほうがnanだと怒られるので、最初の方のnanがない時間帯から始める
        temp = pd.DataFrame(index=pd.date_range(temp_label_data.index[0],(pd.to_datetime(score_date) + timedelta(days = 3)).strftime("%Y-%m-%d") + ' 23:00:00', freq='H'))
        temp_label_data = temp_label_data.join(temp,how="outer")
        label_data_stations[station] = temp_label_data
        logger.warning(station)

    # submit data
    submit_data = pd.read_csv("./submit/static/submit_files/"+submit.username+"/"+submit.filename)
    submit_data['stationId'] = submit_data['test_id'].str.split('#').apply(lambda x:x[0])
    submit_data['hour_num'] = submit_data['test_id'].str.split('#').apply(lambda x:x[1]).astype(int)

    base_datetime = pd.to_datetime(score_date) + timedelta(days = 1)
    temp_submit = submit_data.loc[submit_data['score_date'] == score_date]
    temp_submit['datetime'] = temp_submit['hour_num'].apply(lambda x:base_datetime + timedelta(hours = x))

    submit_data_stations = {}
    for station in label_data_stations.keys():
        submit_data_stations[station] = temp_submit.loc[temp_submit['stationId']==station, ['datetime',target]].set_index('datetime').sort_index()

    charts = []
    for station in sorted(label_data_stations.keys()):
        temp_dict = {'station':station}
        temp_dict['chart_data_series'] = []
        temp_dict['chart_data_series'].append({
            'name':'label',
            'data':str(label_data_stations[station].values.tolist()).replace('nan','null'),
            'start_dt':str(label_data_stations[station].index[0])
            })
        temp_dict['chart_data_series'].append({
            'name':'submit ' + score_date,
            'data':str(submit_data_stations[station].values.tolist()).replace('nan',''),
            'start_dt':base_datetime
            })
        charts.append(temp_dict)

    context = {
        'charts': charts,
        'submit_id': submit_id,
        'submit_timestamp' : submit.submit_timestamp,
        'submit_username' : submit.username,
        'submit_filename' : submit.filename,
        'city' : city,
        'target' : target
    }
    return render(request, 'mysubmission/mysubmission_detail_chart.html', context)

mysubmission/templates/mysubmission/mysubmission_base.html
{% extends "submit/base.html" %}
{% block title %}submit page{% endblock title %}
{% load staticfiles %}

{% block body %}
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-6 full-width margin-top-20percent">
                    <h2 align="center">My Submission Page</h2>
                    Submit結果を検索するよ
                    <form method="POST" onsubmit="return check_blank_mysubmission(this)">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">Username</label>
                            <input type="text" class="form-control" name="username" id="id_username">
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block" value="submit">検索</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysubmission/templates/mysubmission/mysubmission_detail.html
{% extends "submit/base.html" %}
{% block title %}My Submission Detail{% endblock title %}
{% load staticfiles %}
      {% block body %}
      <div id="wrapper">
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-6 full-width margin-top-20percent" >
              <h2 align="center">My Submission Detail</h2>
                    <div class="table-responsive">
                <table id="submit-result-table" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline full-width">
                    <thead>
                      <tr>
                        <th class="score_table">提出日時</th>
                        <th class="score_table">ユーザー名</th>
                        <th class="score_table">ファイル名</th>
                        <th class="score_table">平均スコア</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="score_table">{{submit_timestamp}}</td>
                        <td class="score_table">{{submit_username}}</td>
                        <td class="score_table">{{submit_filename}}</td>
                        <td class="score_table">{{submit_score_avg}}</td>
                      </tr>
                    </tbody>
                  </table>

                  <table id="submit-result-table" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline full-width">
                    <thead>
                      <tr>
                        <th class="score_table" ROWSPAN="3">スコア日</th>
                        <th class="score_table" ROWSPAN="3">スコア</th>
                        <th class="score_table" COLSPAN="5">スコア内訳</th>
                      </tr>
                      <tr>
                        <th class="score_table" COLSPAN="3">北京</th>
                        <th class="score_table" COLSPAN="2">ロンドン</th>
                      </tr>
                      <tr>
                        <th class="score_table">PM2.5</th>
                        <th class="score_table">PM10</th>
                        <th class="score_table">O3</th>
                        <th class="score_table">PM2.5</th>
                        <th class="score_table">PM10</th>
                      </tr>
                      </thead>
                      {% for score in scores %}
                    <tbody>
                      <tr>
                        <td class="score_table">{{score.score_date}}</td>
                        <td class="score_table">{{score.score|floatformat:5 }}</td>
                        <td class="score_table"><a href="{% url 'mysubmission:mysubmission_detail_chart_view' %}?submit_id={{submit_id}}&city=bj&target=PM2.5&score_date={{score.score_date|safe}}">{{score.bj_pm25_score|floatformat:5 }}</a> </td>
                        <td class="score_table"><a href="{% url 'mysubmission:mysubmission_detail_chart_view' %}?submit_id={{submit_id}}&city=bj&target=PM10&score_date={{score.score_date|safe}}">{{score.bj_pm10_score|floatformat:5 }}</a></td>
                        <td class="score_table"><a href="{% url 'mysubmission:mysubmission_detail_chart_view' %}?submit_id={{submit_id}}&city=bj&target=O3&score_date={{score.score_date|safe}}">{{score.bj_o3_score|floatformat:5 }}</a></td>
                        <td class="score_table"><a href="{% url 'mysubmission:mysubmission_detail_chart_view' %}?submit_id={{submit_id}}&city=ld&target=PM2.5&score_date={{score.score_date|safe}}">{{score.ld_pm25_score|floatformat:5 }}</a></td>
                        <td class="score_table"><a href="{% url 'mysubmission:mysubmission_detail_chart_view' %}?submit_id={{submit_id}}&city=bj&target=PM10&score_date={{score.score_date|safe}}">{{score.ld_pm10_score|floatformat:5 }}</a></td>
                      </tr>
                      {% endfor %}
                      <tr>
                        <td colspan="7">
                          {% for chart in charts %}
                          <div id="container_{{chart.city}}_{{chart.target}}" style="min-width: 310px; max-width: 1200px; height: 400px; margin: 0 auto;"></div>
                          <script type="text/javascript">
                            Highcharts.setOptions({
                                global : {
                                    useUTC : false
                                }
                            });
                            Highcharts.chart('container_{{chart.city}}_{{chart.target}}', {
                              title: {
                                  text: '{{chart.city}} {{chart.target}}'
                              },

                              subtitle: {
                                  text: ''
                              },

                              xAxis: {
                                type: 'datetime',
                                dateTimeLabelFormats: {
                                        minute: '%H:%M',
                                        hour: '%m/%d %H:%M',
                                        day: '%Y/%m/%d',
                                        week: '%Y/%m/%d',
                                        month: '%Y/%m',
                                        year: '(%Y)'
                                    }
                              },

                              yAxis: {
                                  title: {
                                      text: '{{chart.target}}'
                                  }
                              },
                              legend: {
                                  layout: 'vertical',
                                  align: 'right',
                                  verticalAlign: 'middle'
                              },

                              plotOptions: {
                                  series: {
                                      label: {
                                          connectorAllowed: false
                                      },
                                      pointStart: 2010
                                  }
                              },

                              series: [
                              {% for chart_data in chart.chart_data_series %}
                              {
                                  name: '{{chart_data.name}}',
                                  data: {{chart_data.data|safe}},
                                  pointStart: Date.parse('{{chart_data.start_dt|safe}}'),
                                  pointInterval: 3600 * 1000
                              },
                              {% endfor %}
                              ],

                              responsive: {
                                  rules: [{
                                      condition: {
                                          maxWidth: 500
                                      },
                                      chartOptions: {
                                          legend: {
                                              layout: 'horizontal',
                                              align: 'center',
                                              verticalAlign: 'bottom'
                                          }
                                      }
                                  }]
                              }
                            });
                          </script>
                          {% endfor %}
                        </td>
                      </tr>
                    </tbody>
                  </table>

            </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}

mysubmission/templates/mysubmission/mysubmission_detail_chart.html
{% extends "submit/base.html" %}
{% block title %}My Submission Detail Chart{% endblock title %}
{% load staticfiles %}
      {% block body %}
      <div id="wrapper">
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-6 full-width margin-top-20percent" >
              <h2 align="center">My Submission Detail Chart {{city}} {{target}}</h2>
                <div class="table-responsive">
                  <table id="submit-result-table" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline full-width">
                    <tbody>
                      <tr>
                        <td colspan="7">
                          {% for chart in charts %}
                          <div id="container_{{chart.station}}" style="min-width: 310px; max-width: 1200px; height: 400px; margin: 0 auto;"></div>
                          <script type="text/javascript">
                            Highcharts.setOptions({
                                global : {
                                    useUTC : false
                                }
                            });
                            Highcharts.chart('container_{{chart.station}}', {
                              title: {
                                  text: '{{city}} {{target}} {{chart.station}}'
                              },

                              subtitle: {
                                  text: ''
                              },

                              xAxis: {
                                type: 'datetime',
                                dateTimeLabelFormats: {
                                        minute: '%H:%M',
                                        hour: '%m/%d %H:%M',
                                        day: '%Y/%m/%d',
                                        week: '%Y/%m/%d',
                                        month: '%Y/%m',
                                        year: '(%Y)'
                                    }
                              },

                              yAxis: {
                                  title: {
                                      text: '{{target}}'
                                  }
                              },
                              legend: {
                                  layout: 'vertical',
                                  align: 'right',
                                  verticalAlign: 'middle'
                              },

                              plotOptions: {
                                  series: {
                                      label: {
                                          connectorAllowed: false
                                      },
                                      pointStart: 2010
                                  }
                              },

                              series: [
                              {% for chart_data in chart.chart_data_series %}
                              {
                                  name: '{{chart_data.name}}',
                                  data: {{chart_data.data|safe}},
                                  pointStart: Date.parse('{{chart_data.start_dt|safe}}'),
                                  pointInterval: 3600 * 1000
                              },
                              {% endfor %}
                              ],

                              responsive: {
                                  rules: [{
                                      condition: {
                                          maxWidth: 500
                                      },
                                      chartOptions: {
                                          legend: {
                                              layout: 'horizontal',
                                              align: 'center',
                                              verticalAlign: 'bottom'
                                          }
                                      }
                                  }]
                              }
                            });
                          </script>
                          {% endfor %}
                        </td>
                      </tr>
                    </tbody>
                  </table>

            </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}

mysubmission/templates/mysubmission/mysubmission_list.html
{% extends "submit/base.html" %}
{% block title %}My Submission List{% endblock title %}
{% load staticfiles %}

      {% block body %}
      <div id="wrapper">
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-6 full-width margin-top-20percent" >
              <h2 align="center">My Submission List</h2>
                <table id="submit-result-table" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline full-width">
                    <thead>
                      <tr>
                        <th class="score_table" ROWSPAN="2">提出日時</th>
                        <th class="score_table" ROWSPAN="2">ユーザー名</th>
                        <th class="score_table" ROWSPAN="2">ファイル名</th>
                        <th class="score_table" COLSPAN="2">スコア期間</th>
                        <th class="score_table" ROWSPAN="2">平均スコア</th>
                        <th class="score_table" ROWSPAN="2">詳細ボタン</th>
                      </tr>
                      <tr>
                        <th class="score_table">開始日</th>
                        <th class="score_table">終了日</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for submit in submits %}
                      <tr>
                        <td class="score_table">{{submit.submit_timestamp}}</td>
                        <td class="score_table">{{submit.username}}</td>
                        <td class="score_table">{{submit.filename}}</td>
                        <td class="score_table">{{submit.score_date_start}}</td>
                        <td class="score_table">{{submit.score_date_end}}</td>
                        <td class="score_table">{{submit.score_avg|floatformat:5 }}</td>
                        <td class="score_table">
                            <form method="GET" action="{% url 'mysubmission:mysubmission_detail_view' %}" >
                                <input type="hidden" name="submit_id" value={{submit.id}}>
                                <button type="submit" class="btn btn-primary btn-block" value="detail">詳細
                                </button>
                            </form>
                        </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}